# Generated by Django 4.2 on 2024-07-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproduccion',
            name='hora_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
